"""empty message

Revision ID: 4267897670ec
Revises: 88f525f89f54
Create Date: 2020-05-01 07:00:52.998439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4267897670ec'
down_revision = '88f525f89f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
